### ISSUE TITLE
pyparsing not included in requirements.txt file so make fails.

### ISSUE THREAD

**Issue by ljreder** [JPLOpenSource/QMAutocoder#1]
After performing the initial install of packages and executing the `make`  I get this error.  The python module pyparsing is missing from the installation.  Here is the error below.

Also recommend instruction for creating a virtual environment and specify Python version required.

After installing pyparsing 3.1.2 both the `make` and `make ut` ran successfully!

Also I recommend in your import of module not to use aliases.  Perhaps talk to Micheal Starch about Python style guides.

ERROR FOLLOW:
````
(QM) reder@pop-os:~/QM/QMAutocoder$ make
make -C models
make[1]: Entering directory '/home/reder/QM/QMAutocoder/models'
make[2]: Entering directory '/home/reder/QM/QMAutocoder/QHsm'
gcc -c -Wall hsm_qf.c -o hsm_qf.o
gcc -c -Wall log_event.c -o log_event.o
ar rs libqhsm.a hsm_qf.o log_event.o
ar: creating libqhsm.a
make[2]: Leaving directory '/home/reder/QM/QMAutocoder/QHsm'
make[2]: Entering directory '/home/reder/QM/QMAutocoder/models/TestModels/simple'
make[3]: Entering directory '/home/reder/QM/QMAutocoder/models/TestModels/simple/C'
**** Running the state-machine autocoder ****
../../../../autocoder/QMAutocoder.py c  -debug ../Simple.qm
Traceback (most recent call last):
  File "/home/reder/QM/QMAutocoder/models/TestModels/simple/C/../../../../autocoder/QMAutocoder.py", line 65, in <module>
    import UmlParser
  File "/home/reder/QM/QMAutocoder/autocoder/UmlParser.py", line 12, in <module>
    import pyparsing as pyparse
ModuleNotFoundError: No module named 'pyparsing'
make[3]: *** [../../Common_C_Makefile:9: autocode] Error 1
make[3]: Leaving directory '/home/reder/QM/QMAutocoder/models/TestModels/simple/C'
make[2]: *** [Makefile:20: c-depend] Error 2
make[2]: Leaving directory '/home/reder/QM/QMAutocoder/models/TestModels/simple'
make[1]: *** [Makefile:138: TestModels/simple-build] Error 2
make[1]: Leaving directory '/home/reder/QM/QMAutocoder/models'
make: *** [Makefile:8: all] Error 2
````

**Comment by garthwatney** [comment]
Fixed: 739f2d4325bde707ffd571c526ba9b2e219003f2
